/** Authenticated, color-scoped Staff dashboard, athlete editor, and print module. */
(function(){
  'use strict';
  const S=Sports,params=new URLSearchParams(location.search),color=params.get('color'),team=S.COLORS[color];let key='',data=null,currentSport='';
  const $=id=>document.getElementById(id),genderLabel={Male:'ชาย',Female:'หญิง',Mixed:'ผสม'};
  if(!team){$('staff-login').innerHTML='<div class="notice">ลิงก์ไม่ถูกต้อง ต้องระบุ color เป็น red, yellow, blue หรือ pink</div>';return}
  $('staff-banner').classList.add('banner-'+color);$('staff-title').textContent=`STAFF ${team.th}`;
  const personName=p=>`${p.prefix||''}${p.firstName||''} ${p.lastName||''}`.trim();
  const initials=name=>String(name||'?').trim().split(/\s+/).map(x=>x[0]||'').slice(0,2).join('')||'?';
  const athleteAvatar=(person,size='medium')=>person.photoUrl?`<span class="athlete-avatar avatar-${size}"><img src="${S.esc(person.photoUrl)}" alt="รูป ${S.esc(person.studentName||personName(person))}" loading="lazy" referrerpolicy="no-referrer"></span>`:`<span class="athlete-avatar avatar-${size} avatar-fallback" aria-hidden="true">${S.esc(initials(person.studentName||personName(person)))}</span>`;
  const athletesFor=id=>(data.athletes||[]).filter(a=>a.sportId===id);
  const allowed=(student,sport)=>{const levels=String(sport.level||'').split(',').map(x=>x.trim()),levelOk=!sport.level||sport.level==='ทุกระดับ'||(sport.level==='ประถม'&&student.level.startsWith('ป.'))||(sport.level==='มัธยม'&&student.level.startsWith('ม.'))||levels.includes(student.level),title=student.prefix||'',male=['นาย','เด็กชาย','ด.ช.'].some(x=>title.startsWith(x)),female=['นางสาว','นาง','เด็กหญิง','ด.ญ.'].some(x=>title.startsWith(x)),genderOk=sport.gender==='Mixed'||(sport.gender==='Male'&&male)||(sport.gender==='Female'&&female);return levelOk&&genderOk};
  async function login(){key=$('staff-key').value.trim();if(!key)return;const button=$('staff-login-btn');button.disabled=true;button.textContent='กำลังเข้าสู่ระบบ…';try{data=await S.api('getStaffData',{color,staffKey:key},'POST');$('staff-login').hidden=true;$('staff-app').hidden=false;render()}catch(e){$('staff-login-error').hidden=false;$('staff-login-error').textContent=e.message}finally{button.disabled=false;button.textContent='เข้าสู่ระบบ'}}
  $('staff-login-btn').onclick=login;$('staff-key').onkeydown=e=>{if(e.key==='Enter')login()};
  document.querySelectorAll('.staff-menu button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.staff-menu button,.staff-view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('staff-'+b.dataset.view).classList.add('active')});
  function render(){const open=data.staffRegistrationOpen!==false,full=(data.sports||[]).filter(s=>athletesFor(s.id).length>=Number(s.athleteLimit)).length;$('staff-status').className='notice '+(open?'staff-open':'staff-closed');$('staff-status').textContent=open?'🟢 ระบบเปิดรับ: เพิ่ม ลบ และเปลี่ยนนักกีฬาได้จนกว่าจะครบโควตา':'🔒 แอดมินปิดระบบแล้ว: ดูข้อมูล ผลการแข่งขัน และสั่งพิมพ์ได้เท่านั้น';$('staff-overview').innerHTML=`<div class="staff-stat-grid"><article class="sports-card"><strong>${data.students.length}</strong><span>นักเรียนในสี</span></article><article class="sports-card"><strong>${data.teachers.length}</strong><span>ครูประจำสี</span></article><article class="sports-card"><strong>${data.athletes.length}</strong><span>รายการนักกีฬา</span></article><article class="sports-card"><strong>${full}/${data.sports.length}</strong><span>กีฬาที่ลงครบ</span></article></div><h2 class="section-title">สถานะกีฬา</h2><div class="grid grid-2">${data.sports.map(s=>sportCard(s)).join('')}</div>`;renderStudents();renderTeachers();renderRegister();renderAthletes();renderResults()}
  function sportCard(s){const count=athletesFor(s.id).length,max=Number(s.athleteLimit),complete=count>=max;return`<article class="sports-card"><h3>${S.esc(s.name)}</h3><div class="meta"><span class="chip">${S.esc(s.level)}</span><span class="chip">${genderLabel[s.gender]||S.esc(s.gender)}</span></div><div class="quota"><span style="width:${Math.min(100,count/max*100)}%"></span></div><p class="quota-copy ${complete?'complete':''}">${count} / ${max} คน · ${complete?'ครบแล้ว':'เหลือ '+(max-count)+' คน'}</p></article>`}
  function rosterTable(items,type){return`<div class="table-wrap"><table class="data-table"><thead><tr><th>ลำดับ</th><th>ชื่อ–สกุล</th><th>${type==='student'?'ชั้น/ห้อง':'หน้าที่'}</th></tr></thead><tbody>${items.map((p,i)=>`<tr><td>${i+1}</td><td>${S.esc(personName(p))}</td><td>${type==='student'?S.esc(p.level+'/'+p.room):S.esc(p.role||'-')}</td></tr>`).join('')}</tbody></table></div>`}
  /** Student directory filters rooms only after a level is selected. */
  function renderStudents(){const root=$('staff-students'),levels=[...new Set(data.students.map(x=>x.level).filter(Boolean))].sort();root.innerHTML=`<div class="section-head"><h2>นักเรียน${team.th}</h2><button class="secondary" data-print="students">🖨️ พิมพ์เช็กชื่อ</button></div><div class="student-filters"><div class="field"><label>ระดับชั้น</label><select id="student-level">${S.options(levels.map(x=>({id:x,name:x})),'id','name','ทุกระดับชั้น')}</select></div><div class="field"><label>ห้อง</label><select id="student-room" disabled><option value="">ทุกห้อง</option></select></div></div><div id="filtered-students"></div>`;let shown=data.students;const draw=()=>{$('filtered-students').innerHTML=rosterTable(shown,'student');root.querySelector('[data-print]').onclick=()=>printRoster('รายชื่อนักเรียน',shown.map(x=>({name:personName(x),detail:x.level+'/'+x.room})))};$('student-level').onchange=()=>{const level=$('student-level').value,rooms=[...new Set(data.students.filter(x=>x.level===level).map(x=>x.room).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'th',{numeric:true}));$('student-room').innerHTML=S.options(rooms.map(x=>({id:x,name:'ห้อง '+x})),'id','name','ทุกห้อง');$('student-room').disabled=!level;shown=level?data.students.filter(x=>x.level===level):data.students;draw()};$('student-room').onchange=()=>{const level=$('student-level').value,room=$('student-room').value;shown=data.students.filter(x=>(!level||x.level===level)&&(!room||x.room===room));draw()};draw()}
  function renderTeachers(){$('staff-teachers').innerHTML=`<div class="section-head"><h2>ครู${team.th}</h2><button class="secondary" data-print="teachers">🖨️ พิมพ์เช็กชื่อ</button></div>${rosterTable(data.teachers,'teacher')}`;$('staff-teachers').querySelector('[data-print]').onclick=()=>printRoster('รายชื่อครู',data.teachers.map(x=>({name:personName(x),detail:x.role||'-'})))}
  function renderRegister(){const root=$('staff-register');root.innerHTML=`<h2>ลงทะเบียนนักกีฬา</h2><p class="muted">ระบบแสดงเฉพาะนักเรียนที่ตรงกับสี เพศ และระดับชั้นของกีฬา</p><div class="grid grid-2">${data.sports.map(s=>`<button class="sport-choice" data-sport="${s.id}">${sportCard(s)}</button>`).join('')}</div><div id="staff-picker"></div>`;root.querySelectorAll('[data-sport]').forEach(b=>b.onclick=()=>openPicker(b.dataset.sport))}
  /** Two-zone athlete picker: tapping a name moves it between available and selected lists. */
  function openPicker(id){currentSport=id;const sport=data.sports.find(s=>s.id===id),eligible=data.students.filter(st=>allowed(st,sport)),selected=new Set(athletesFor(id).map(a=>a.studentId)),max=Number(sport.athleteLimit),open=data.staffRegistrationOpen!==false,picker=$('staff-picker');picker.innerHTML=`<article class="sports-card picker"><div class="section-head picker-head"><div><h2>${S.esc(sport.name)}</h2><p>${S.esc(sport.level)} · ${genderLabel[sport.gender]} · รับ ${max} คน</p></div><div class="picker-head-actions"><strong id="picker-count"></strong><button id="staff-save-athletes" class="primary" ${open?'':'disabled'}>💾 บันทึกรายชื่อ</button></div></div><section class="athlete-zone selected-zone"><h3>รายชื่อนักกีฬา <span id="selected-label"></span></h3><div id="selected-athletes" class="athlete-name-grid"></div></section><section class="athlete-zone"><h3>รายชื่อที่ผ่านเงื่อนไข</h3><p class="muted">แตะชื่อเพื่อเพิ่มเป็นนักกีฬา</p><div id="available-athletes" class="athlete-name-grid"></div></section></article>`;
    const nameButton=(st,isSelected)=>`<button type="button" class="athlete-name ${isSelected?'is-selected':''}" data-student="${S.esc(st.id)}" ${open?'':'disabled'}><span class="athlete-choice-avatar">${athleteAvatar(st,'small')}<i>${isSelected?'✓':'+'}</i></span><b>${S.esc(personName(st))}</b><small>${S.esc(st.level+'/'+st.room)} · เลขที่ ${S.esc(st.number)}</small></button>`;
    const drawPicker=()=>{const chosen=eligible.filter(st=>selected.has(st.id)),available=eligible.filter(st=>!selected.has(st.id)),full=selected.size>=max,emptySlots=Array.from({length:Math.max(0,max-chosen.length)},(_,i)=>`<div class="athlete-empty-slot"><span>${chosen.length+i+1}</span><b>ว่าง</b><small>ยังไม่ได้เลือกนักกีฬา</small></div>`).join('');$('picker-count').textContent=`${selected.size}/${max}`;$('selected-label').textContent=`(${selected.size}/${max} คน)`;$('selected-athletes').innerHTML=chosen.map(st=>nameButton(st,true)).join('')+emptySlots;$('available-athletes').innerHTML=available.length?available.map(st=>nameButton(st,false)).join(''):'<div class="empty-state">ไม่มีรายชื่อที่เลือกได้</div>';picker.querySelectorAll('[data-student]').forEach(button=>{const isSelected=selected.has(button.dataset.student);button.disabled=!open||(!isSelected&&full);button.onclick=()=>{if(isSelected)selected.delete(button.dataset.student);else if(selected.size<max)selected.add(button.dataset.student);else return S.toast(`รับได้ไม่เกิน ${max} คน`);drawPicker()}})};drawPicker();$('staff-save-athletes').onclick=async()=>{try{await S.api('saveAthletes',{sportId:id,color,studentIds:[...selected],userType:'Staff',staffKey:key},'POST');S.toast('บันทึกรายชื่อนักกีฬาแล้ว');data=await S.api('getStaffData',{color,staffKey:key},'POST');render();document.querySelector('[data-view=register]').click();openPicker(id)}catch(e){S.toast(e.message)}};picker.scrollIntoView({behavior:'smooth'})}
  function renderAthletes(){const root=$('staff-athletes');root.innerHTML=`<div class="section-head"><h2>รายชื่อนักกีฬา</h2><button class="secondary" id="print-all-athletes">🖨️ พิมพ์ทุกกีฬา</button></div><div class="grid grid-2">${data.sports.map(s=>{const rows=athletesFor(s.id);return`<article class="sports-card"><div class="section-head"><div><h3>${S.esc(s.name)}</h3><p>${rows.length}/${s.athleteLimit} คน</p></div><button class="secondary" data-print-sport="${s.id}">พิมพ์</button></div>${rows.map(a=>`<div class="public-person athlete-person">${athleteAvatar(a)}<span>${S.esc(a.studentName)}<small class="person-role">${S.esc(a.levelRoom)}</small></span></div>`).join('')||'<div class="empty-state">ยังไม่มีรายชื่อ</div>'}</article>`}).join('')}</div>`;root.querySelectorAll('[data-print-sport]').forEach(b=>b.onclick=()=>printSports([b.dataset.printSport]));$('print-all-athletes').onclick=()=>printSports(data.sports.map(s=>s.id))}
  function renderResults(){$('staff-results').innerHTML=`<h2>ผลการแข่งขันของทีม</h2><div class="grid">${data.matches.map(m=>`<article class="sports-card"><h3>${S.esc(m.sportName)} · ${S.esc(m.round)}</h3><p>${S.team(m.teamA)} <b>${m.scoreA===''?'–':m.scoreA+' – '+m.scoreB}</b> ${S.team(m.teamB)}</p><div class="meta"><span class="status ${m.status==='Confirmed'?'status-confirmed':''}">${m.status==='Confirmed'?'ยืนยันแล้ว':'รอแข่งขัน'}</span>${m.referee?`<span class="chip">กรรมการ ${S.esc(m.referee)}</span>`:''}</div></article>`).join('')||'<div class="empty-state">ยังไม่มีคู่แข่งขันของทีมนี้</div>'}`}
  function checkHeaders(){return Array.from({length:15},(_,i)=>`<th>${i+1}</th>`).join('')}
  function checkCells(){return'<td></td>'.repeat(15)}
  function printSection(title,rows){return`<section class="staff-print-section"><header><h1>${S.esc(title)} ${S.esc(team.th)}</h1><p>กีฬาโรงเรียนบ้านห้วยผึ้ง ปีการศึกษา 2569 &nbsp; วันที่ __________ ผู้ตรวจ __________</p></header><table><thead><tr><th>ที่</th><th>ชื่อ–สกุล</th><th>ชั้น/หน้าที่</th>${checkHeaders()}</tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${S.esc(r.name)}</td><td>${S.esc(r.detail)}</td>${checkCells()}</tr>`).join('')}</tbody></table></section>`}
  function doPrint(html){$('staff-print-area').innerHTML=html;document.body.classList.add('staff-printing');window.print();setTimeout(()=>document.body.classList.remove('staff-printing'),300)}
  function printRoster(title,rows){doPrint(printSection(title,rows))}
  function printSports(ids){doPrint(ids.map(id=>{const s=data.sports.find(x=>x.id===id);return printSection('รายชื่อนักกีฬา '+s.name,athletesFor(id).map(a=>({name:a.studentName,detail:a.levelRoom}))) }).join(''))}
})();
